default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  # host: db

development:
  <<: *default
  database: dream_rent_api_development

test:
  <<: *default
  database: dream_rent_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: dream_rent_api_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
